name: Lint and push to itchio

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  build_artifacts:
    needs: linting
    if: ${{ github.event_name == 'push' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            CHANNEL: windows
            SEPARATOR: ';'

          - os: macos-latest
            CHANNEL: osx
            SEPARATOR: ':'

          - os: ubuntu-latest
            CHANNEL: linux
            SEPARATOR: ':'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller -w --add-data "assets${{ matrix.SEPARATOR }}assets" --add-data "models${{ matrix.SEPARATOR }}models" --add-data "UI${{ matrix.SEPARATOR }}UI" --add-data "src${{ matrix.SEPARATOR }}src" --add-data ".meta${{ matrix.SEPARATOR }}.meta" --add-data "Stormtrays.py${{ matrix.SEPARATOR }}." Stormtrays.py

    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.CHANNEL }}-artifact
        path: artifact

  push_butler:
    needs: build_artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [linux, osx, windows]

    steps:  
    - uses: actions/download-artifact@master
      with:
        name: ${{ matrix.channel }}-artifact
        path: artifact

    - uses: josephbmanley/butler-publish-itchio-action@master
    - name: itch-io linux publish
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: ${{ matrix.channel }}
        ITCH_GAME: stormtrays
        ITCH_USER: Minigrim0
        PACKAGE: dist/Stormtrays/
